//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit app.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make favourite.
        /// </summary>
        public static string btnPickFavTeam {
            get {
                return ResourceManager.GetString("btnPickFavTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string btnShowOppTeamDetails {
            get {
                return ResourceManager.GetString("btnShowOppTeamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player details.
        /// </summary>
        public static string btnShowPlayerDetails {
            get {
                return ResourceManager.GetString("btnShowPlayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string btnShowTeamDetails {
            get {
                return ResourceManager.GetString("btnShowTeamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string genderHeader {
            get {
                return ResourceManager.GetString("genderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string languageHeader {
            get {
                return ResourceManager.GetString("languageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite team:.
        /// </summary>
        public static string lblFavTeamLbl {
            get {
                return ResourceManager.GetString("lblFavTeamLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams played against:.
        /// </summary>
        public static string lblOpponentTeams {
            get {
                return ResourceManager.GetString("lblOpponentTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick team:.
        /// </summary>
        public static string lblPickTeam {
            get {
                return ResourceManager.GetString("lblPickTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string lblResult {
            get {
                return ResourceManager.GetString("lblResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string rbtnCroatian {
            get {
                return ResourceManager.GetString("rbtnCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string rbtnEnglish {
            get {
                return ResourceManager.GetString("rbtnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string rbtnFemale {
            get {
                return ResourceManager.GetString("rbtnFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string rbtnFullscreen {
            get {
                return ResourceManager.GetString("rbtnFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string rbtnLarge {
            get {
                return ResourceManager.GetString("rbtnLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string rbtnMale {
            get {
                return ResourceManager.GetString("rbtnMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meddium.
        /// </summary>
        public static string rbtnMid {
            get {
                return ResourceManager.GetString("rbtnMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string rbtnSmall {
            get {
                return ResourceManager.GetString("rbtnSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen size.
        /// </summary>
        public static string screenSizeHeader {
            get {
                return ResourceManager.GetString("screenSizeHeader", resourceCulture);
            }
        }
    }
}
